# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|  
  (1..1).each do |i|
    config.vm.define "etcd-#{i}" do |m|
      m.vm.box = "ubuntu/xenial64"
      config.vm.network "private_network", type: "dhcp"

      config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end

      config.vm.provision "shell",
      run: "always",
      inline: "echo 'etcd-#{i}' | sudo tee /etc/hostname"

      config.vm.provision "shell", path: "../scripts/etcd.sh", args: "#{$i}"
    end
  end
end
